### ISSUE TITLE
工程用不了,不能学习喽

### ISSUE THREAD

**Issue by zzdota** [NJHu/iOSProject#41]
工程用不了,pod方式出错,  直接下载文件的方式,下载后,编译也是出错.
作者让别人去学习的初衷没有实现喽.
希望作者处理一下.

**Comment by MrStock007** [comment]
是的，为啥跑不起来，很纳闷

**Comment by karven** [comment]
### Error

```
LoadError - cannot load such file -- i18n/backend/simple
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Library/Ruby/Gems/2.3.0/gems/i18n-0.9.5/lib/i18n/config.rb:19:in `backend'
/Library/Ruby/Gems/2.3.0/gems/i18n-0.9.5/lib/i18n.rb:247:in `transliterate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.0.beta.2/lib/cocoapods-core/specification.rb:192:in `c99ext_identifier'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.0.beta.2/lib/cocoapods-core/specification.rb:175:in `module_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/target/pod_target.rb:142:in `product_module_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/target/pod_target.rb:331:in `module_map_path'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:185:in `block (2 levels) in install_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:184:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:184:in `block in install_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:178:in `install_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:67:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:209:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:208:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:139:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command/update.rb:97:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

**Comment by NJHu** [comment]
可以了, 您再试试

**Comment by zzdota** [comment]
> 可以了, 您再试试

<img width="666" alt="image" src="https://user-images.githubusercontent.com/16704305/48888692-774abc80-ee6e-11e8-8343-871e12a90414.png">

**Comment by zzdota** [comment]
> 可以了, 您再试试

谢谢楼主哈.刚刚重试了一下,真的可以了.

第一次pod,失败了. 然后pod update一下,就成功了.工程跑起来啦!
亲们,可以学起来啦~~可以燥起来啦~~
